### ISSUE TITLE
Zod error on valid international address in v2.2.9 latitude/longitude types

### ISSUE THREAD

**Issue by alsoscotland** [goshippo/shippo-javascript-sdk#53]
I am seeing a zod validation error on valid international address data in v2.2.9

using the `addresses.create` method on the SDK

```js
{
        "type": "SDKValidationError",
        "message": "Response validation failed: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"string\",\n    \"path\": [\n      \"latitude\"\n    ],\n    \"message\": \"Expected number, received string\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"string\",\n    \"path\": [\n      \"longitude\"\n    ],\n    \"message\": \"Expected number, received string\"\n  }\n]",
        "stack":
            SDKValidationError: Response validation failed
                at parse ({REDACTED}node_modules/shippo/src/lib/schemas.ts:18:19)
                at ResponseMatcher.match ({REDACTED}node_modules/shippo/src/lib/http.ts:477:27)
                at processTicksAndRejections (node:internal/process/task_queues:95:5)
                at async Addresses.create ({REDACTED}node_modules/shippo/src/sdk/addresses.ts:192:27)
                {LOCAL_CODE_INFO_REDACTED}
            caused by: ZodError: [
              {
                "code": "invalid_type",
                "expected": "number",
                "received": "string",
                "path": [
                  "latitude"
                ],
                "message": "Expected number, received string"
              },
              {
                "code": "invalid_type",
                "expected": "number",
                "received": "string",
                "path": [
                  "longitude"
                ],
                "message": "Expected number, received string"
              }
            ]
                at Object.get error [as error] ({REDACTED}node_modules/zod/lib/types.js:55:31)
                at ZodEffects.parse ({REDACTED}node_modules/zod/lib/types.js:160:22)
                at {REDACTED}node_modules/shippo/src/lib/http.ts:477:57
                at parse ({REDACTED}node_modules/shippo/src/lib/schemas.ts:15:16)
                at ResponseMatcher.match ({REDACTED}node_modules/shippo/src/lib/http.ts:477:27)
                {LOCAL_CODE_INFO_REDACTED}
        "name": "SDKValidationError",
        "rawValue": {
          "object_created": "2024-06-06T20:57:41.790Z",
          "object_updated": "2024-06-06T20:57:41.838Z",
          "object_id": "c4919812272b4b4db7dfacfc500fb347",
          "is_complete": true,
          "validation_results": {
            **"is_valid": true,**
            "messages": [
              {
                "source": "Shippo Address Validator",
                "code": "premises_full",
                "type": "address_warning",
                "text": "The address has been verified to the Premise (House or Building) Level, which is the highest level possible with the reference data."
              },
              {
                "source": "Shippo Address Validator",
                "code": "geocoded_rooftop",
                "type": "geocode_level",
                "text": "The record was geocoded down to rooftop level, meaning the point is within the property boundaries (most often the center)."
              }
            ]
          },
          "object_owner": "{REDACTED}",
          "name": "{REDACTED}",
          "company": "",
          "street_no": "",
          "street1": "{REDACTED}",
          "street2": "",
          "street3": "",
          "city": "{REDACTED}",
          "state": "{REDACTED}",
          "zip": "{REDACTED}",
          "country": "{REDACTED}",
          "longitude": "{REDACTED}",
          "latitude": "{REDACTED}",
          "phone": "{REDACTED}",
          "email": "",
          "metadata": "",
          "test": false
        }
      },
      "status": 400
    }
```

**Comment by loresclement** [comment]
Hello,
It look like it's a type problem, could you please share the code that create the address ? 
In the error stack I can read "Expected number, received string" so it means you sent a string for the latitude. It should be a number 

Use parseFloat(yourLatitude) before creating the address with the sdk

**Comment by alsoscotland** [comment]
@loresclement 
I am not sending any latitude or longitude data in these requests. The last couple of these zod errors I have run into have been deserialization errors. Any chance this is and issue with parsing or deserializing a response?

**Comment by shippo-lueders** [comment]
I'm taking a look, should have something to report later today.

**Comment by shippo-lueders** [comment]
okay, it looks like this inconsistent behavior has been in place for a while (validated international addresses returning string instead of number), and since it's been around for so long, it's likely that clients are relying on this behavior so 'fixing' it would potentially cause more problems than it resolves.  

I'm going to update the client to handle lat/long as either a string or a number, will close this issue once the fix is published.

**Comment by alsoscotland** [comment]
@shippo-lueders Sounds good. Thank you for taking a look

**Comment by shippo-lueders** [comment]
should be fixed in https://www.npmjs.com/package/shippo/v/2.3.0
